---
title: "p8105_final_project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(httr)
library(tidyverse)
library(rjson)
library(tidyr)
library(readr)
library(dplyr)
library(jsonlite)
library(stringr)
library(forcats)
library(viridis)
## Loading required package: viridisLite

library(plotly)
```

# Getting Data of Restaurant in business.json
```{r}
business <- stream_in(file("../data/business.json"))

rest.dat = business %>%
  select(-attributes,-hours) %>%
  mutate(categories = as.character(categories)) %>%
  filter(str_detect(categories, "Restaurants")) %>%
  filter(state == "AZ") 

# review <- stream_in(file("../data/review.json"))
```

```{r}
rest.dat %>%
  mutate(text_label = str_c("Postal code: ", postal_code, '\nAddress: ', address, '\nName:',name)) %>% 
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~city,
          text = ~text_label)

```

```{r}
common_city =
  rest.dat %>% 
  count(city, sort = TRUE) %>% 
  top_n(10) %>% 
  select(city)
## Selecting by n

inner_join(rest.dat, common_city,
             by = "city") %>% 
  mutate(city = fct_reorder(city, review_count)) %>% 
  plot_ly(y = ~review_count, color = ~city, type = "box",
          colors = "Set2")
```

```{r}
rest.dat %>% 
  count(city) %>% 
  mutate(city = fct_reorder(city, n)) %>% 
  plot_ly(x = ~city, y = ~n, color = ~city, type = "bar")

```


